### ISSUE TITLE
Loading can-list after can-map-define breaks type: "*"

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-list#33]
If `can-list` is imported after `can-map-define`, using `type: "*"` does not prevent arrays from being converted to `List`s. This is because `can-list` overwrites `Map.prototype.__type` [here](https://github.com/canjs/can-list/blob/master/can-list.js#L957-L970), which always converts to `Array`s to `List`s.

Here is an example showing the problem:
```
import CanMap from "can-map";
import 'can-map-define';

// adding this import after `can-map-define` causes issue
import 'can-list';

var MyMap = CanMap.extend({
  define: {
    anArray: {
      type: '*',
      value(){
        return [ 'a', 'b', 'c' ];
      }
    }
  }
});

var myMap = new MyMap();
myMap.attr('anArray'); // this is a `List`
```

**Comment by ccummings** [comment]
It's not just `*` where this behavior shows and causes problems...

Any call to `Map.prototype.__type` on something Array-like will go through `can-list`'s version of `__type` instead of `can-map-define`'s. Essentially anything Array-like is going to be turned into a List regardless of any `type` or `Type`.

I tried forcing can-list to be a dependency of can-map-define but that doesn't solve the order in which the two files are evaluated.

**Comment by ccummings** [comment]
Making `can-list` a dependency of `can-map-define` solves this issue ([branch](https://github.com/canjs/can-map-define/tree/fix-can-list-type-order)).

Not sure of that is the right fix though...

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-map-define/pull/31.
